// Generated by BUCKLESCRIPT VERSION 1.8.2, PLEASE EDIT WITH CARE
'use strict';

var React       = require("react");
var HeaderSub   = require("./headerSub.js");
var MainTable   = require("./mainTable.js");
var HeaderItem  = require("./headerItem.js");
var SearchItem  = require("./searchItem.js");
var ReasonReact = require("reason-react/lib/js/src/reasonReact.js");

var component = ReasonReact.statelessComponent("App");

function se(prim) {
  return prim;
}

function make(_, _$1) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", {
                  className: "App"
                }, ReasonReact.element(/* None */0, /* None */0, HeaderItem.make("header", /* array */[])), ReasonReact.element(/* None */0, /* None */0, HeaderSub.make("subheader", /* array */[])), ReasonReact.element(/* None */0, /* None */0, SearchItem.make("search", /* array */[])), React.createElement("main", undefined, ReasonReact.element(/* None */0, /* None */0, MainTable.make("table", /* array */[]))));
    });
  return newrecord;
}

exports.component = component;
exports.se        = se;
exports.make      = make;
/* component Not a pure module */
