// Generated by BUCKLESCRIPT VERSION 1.8.2, PLEASE EDIT WITH CARE
'use strict';

var React       = require("react");
var ReasonReact = require("reason-react/lib/js/src/reasonReact.js");

var component = ReasonReact.statelessComponent("HeaderSub");

function se(prim) {
  return prim;
}

function make(_, _$1) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("nav", undefined, React.createElement("div", {
                      className: "hs-select"
                    }, React.createElement("select", undefined, React.createElement("option", undefined, "Callback"), React.createElement("option", undefined, "Show All"), React.createElement("option", undefined, "Pending"))), React.createElement("ul", undefined, React.createElement("li", undefined, "Dashboard"), React.createElement("li", undefined, "Issues"), React.createElement("li", undefined, "Releases")));
    });
  return newrecord;
}

exports.component = component;
exports.se        = se;
exports.make      = make;
/* component Not a pure module */
