// Generated by BUCKLESCRIPT VERSION 1.8.2, PLEASE EDIT WITH CARE
'use strict';

var React       = require("react");
var ReasonReact = require("reason-react/lib/js/src/reasonReact.js");

var component = ReasonReact.statelessComponent("HeaderItem");

function se(prim) {
  return prim;
}

function make(_, _$1) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("header", {
                  className: "bg--gun-metal"
                }, React.createElement("div", {
                      className: "logo animated tada"
                    }, React.createElement("svg", {
                          height: "24",
                          width: "24",
                          viewBox: "0 0 24 24"
                        }, React.createElement("path", {
                              d: "M19 1H5c-1.1 0-1.99.9-1.99 2L3 15.93c0 .69.35 1.3.88 1.66L12 23l8.11-5.41c.53-.36.88-.97.88-1.66L21 3c0-1.1-.9-2-2-2zm-9 15l-5-5 1.41-1.41L10 13.17l7.59-7.59L19 7l-9 9z"
                            }))), React.createElement("div", {
                      className: "topmenu"
                    }, React.createElement("div", {
                          className: "mitem"
                        }, "Lists"), React.createElement("div", {
                          className: "mitem"
                        }, "Settings"), React.createElement("div", {
                          className: "mitem shop"
                        }, React.createElement("svg", {
                              height: "24",
                              width: "24",
                              viewBox: "0 0 24 24"
                            }, React.createElement("path", {
                                  d: "M7 18c-1.1 0-1.99.9-1.99 2S5.9 22 7 22s2-.9 2-2-.9-2-2-2zM1 2v2h2l3.6 7.59-1.35 2.45c-.16.28-.25.61-.25.96 0 1.1.9 2 2 2h12v-2H7.42c-.14 0-.25-.11-.25-.25l.03-.12.9-1.63h7.45c.75 0 1.41-.41 1.75-1.03l3.58-6.49c.08-.14.12-.31.12-.48 0-.55-.45-1-1-1H5.21l-.94-2H1zm16 16c-1.1 0-1.99.9-1.99 2s.89 2 1.99 2 2-.9 2-2-.9-2-2-2z"
                                })))));
    });
  return newrecord;
}

exports.component = component;
exports.se        = se;
exports.make      = make;
/* component Not a pure module */
