// Generated by BUCKLESCRIPT VERSION 1.8.2, PLEASE EDIT WITH CARE
'use strict';

var React       = require("react");
var ReasonReact = require("reason-react/lib/js/src/reasonReact.js");

var component = ReasonReact.statelessComponent("MainTable");

function se(prim) {
  return prim;
}

function make(_, _$1) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("table", {
                  className: "card"
                }, React.createElement("tr", {
                      className: "table-header"
                    }, React.createElement("td", undefined, "Number"), React.createElement("td", undefined, "Name"), React.createElement("td", undefined, "Age"), React.createElement("td", undefined, "Job")), React.createElement("tr", undefined, React.createElement("td", undefined, "521"), React.createElement("td", undefined, "Ben"), React.createElement("td", undefined, "23"), React.createElement("td", undefined, "Front End Dev")), React.createElement("tr", undefined, React.createElement("td", undefined, "951"), React.createElement("td", undefined, "Zoe"), React.createElement("td", undefined, "21"), React.createElement("td", undefined, "Care Worker")));
    });
  return newrecord;
}

exports.component = component;
exports.se        = se;
exports.make      = make;
/* component Not a pure module */
