// Generated by BUCKLESCRIPT VERSION 1.8.2, PLEASE EDIT WITH CARE
'use strict';

var React       = require("react");
var ReasonReact = require("reason-react/lib/js/src/reasonReact.js");

var component = ReasonReact.statelessComponent("SearchItem");

function se(prim) {
  return prim;
}

function make(_, _$1) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", {
                  className: "subnav"
                }, React.createElement("div", {
                      className: "sn-item sn-btn"
                    }, React.createElement("button", {
                          className: "btn--raised btn-blue"
                        }, "Bookmarks"), React.createElement("button", {
                          className: "btn--raised btn-blue"
                        }, "Assigned")), React.createElement("div", {
                      className: "sn-item"
                    }, React.createElement("input", {
                          placeholder: "Search",
                          type: "text"
                        })));
    });
  return newrecord;
}

exports.component = component;
exports.se        = se;
exports.make      = make;
/* component Not a pure module */
