// Generated by BUCKLESCRIPT VERSION 1.8.2, PLEASE EDIT WITH CARE
'use strict';

var React       = require("react");
var ReasonReact = require("reason-react/lib/js/src/reasonReact.js");

var component = ReasonReact.statelessComponent("App");

function se(prim) {
  return prim;
}

function make(_, _$1) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", {
                  className: "App"
                }, React.createElement("div", {
                      className: "App-header"
                    }, React.createElement("h1", undefined, "Reason Projects")));
    });
  return newrecord;
}

exports.component = component;
exports.se        = se;
exports.make      = make;
/* component Not a pure module */
